name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Download Plenti
        run: wget https://github.com/plentico/plenti/releases/download/v0.7.25/plenti_0.7.25_linux_64-bit.tar.gz
        
      - name: Unpack Plenti
        run: tar -zxvf plenti_0.7.25_linux_64-bit.tar.gz
        
      - name: Install node packages
        run: npm install

      - name: Build
        run: ./plenti build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
